"""
Writes the per-class generated C++ constants header (docs/potency-system.md's "Script numbers"
tier 3; PLAN P2b). `src/server/game/Entities/Unit/Generated/<Class>Data.h` holds `constexpr`
spell/creature ids named from the DSL variable that declared them (`shadow_bolt_686` ->
`SPELL_SHADOW_BOLT` - see `_derive_const_name`) plus `const()`'s hand-named values - the generated
counterpart to a hand-maintained file like `WarlockMechanics.h`'s 312 spell-id `constexpr`s, so a
typo'd id stops being possible once a class pass adopts it (PLAN P2b step 4 - that adoption, and
deleting the hand-typed ids it replaces, is P4, not this file).

Deliberately does **not** emit `talent()`'s own `Talent.dbc` row id. Nothing in this codebase's
C++ ever wants that id - a script that cares about a specific talent rank wants *that rank's spell
id* (checked via `HasAura`/`HasSpell`), which is already a `spell()` declaration with its own
variable name, covered by the spell-id case below. Emitting the abstract Talent.dbc id as well
would be dead weight at best and an attractive nuisance at worst (nothing stops someone from
`HasAura(TALENT_SOMETHING)` with the wrong kind of id). `WarlockMechanics.h`'s own existing
`TALENT_*` constants confirm this: every one of them already holds a spell id, never a Talent.dbc
row id.

This module only formats; `lib/dsl/registry.py`'s `_collect_var_names()` (module-namespace
introspection, not AST - see its own docstring) and `const()` already did the real collection work
onto the `Registry`/`load_classes_dir()` output this reads.
"""

from __future__ import annotations

import re
from pathlib import Path

GENERATED_HEADER_MARKER = "// Generated by apps/dbc-tools/generate.py - DO NOT EDIT BY HAND."

_TRAILING_ID_RE = re.compile(r"_\d+$")

# X2 reports only a clash with a NON-rank-style winner (a different spell Name); intentional rank
# chains (same Name, e.g. zeal_201441 vs zeal_20049) stay silent whatever their ids.

# X2 only reports for classes listed here (warlock's pre-existing custom-id rank clashes would
# otherwise print ~40 lines, and the WP-C gate needs zero WARNING lines). Extend per class pass.
WARN_CLASSES = ("paladin",)


def _derive_const_name(var_name: str, prefix: str) -> str:
    """`"shadow_bolt_686"` -> `"SPELL_SHADOW_BOLT"` (prefix `"SPELL_"`) - strips the trailing
    `_<id>` suffix (the id is already the constant's value, repeating it in the name is just
    noise), then upper-cases what's left."""
    stripped = _TRAILING_ID_RE.sub("", var_name)
    return f"{prefix}{stripped.upper()}"


def _cpp_literal(value, cpp_type: str) -> str:
    if cpp_type == "float":
        return f"{float(value)}f"
    return str(int(value))


def _render_id_section(
    ids: list[int], var_names: dict[int, str], prefix: str,
    names: dict[int, str] | None = None, warnings: list[str] | None = None,
) -> list[str]:
    """One `constexpr uint32 <NAME> = <id>;` line per id with a known DSL variable name, in `ids`'
    (already-sorted, so deterministic run to run) order. Multi-rank talents are routinely declared
    as `nightfall_18094`, `nightfall_18095`, `nightfall_200766` - same base name, different ids -
    so `_derive_const_name`'s stripped short form collides constantly in practice, not just in
    theory (confirmed against the real warlock source: 100+ short-name collisions on the first
    real run). The first id to claim a short name keeps it; every id that would collide falls back
    to the *unstripped* var name instead (`SPELL_NIGHTFALL`, then `SPELL_NIGHTFALL_18095`,
    `SPELL_NIGHTFALL_200766`) - guaranteed unique, since var names that differ only by their
    trailing id are themselves already unique (ids are).

    X2 (paladin-rework SHARED B6 item 7): when `warnings` is given, an id that loses its short name
    to a lower id appends one `header: ...` line to it (a warning only - the fallback name is still
    emitted). Shown only when the winner is not a rank-style sibling - `names` (id -> spell name) tells the two apart: ranks of
    one spell share a Name, so `nightfall_18094`/`nightfall_18095` losing the short name is
    expected noise, while `unleash_<seal>` vs `unleash_<seal>_aoe` style clashes carry different
    names and are the real "I expected SPELL_X" surprise."""
    used: set[str] = set()
    owner: dict[str, int] = {}
    lines = []
    for item_id in ids:
        var_name = var_names.get(item_id)
        if var_name is None:
            continue  # no DSL variable found for this id (e.g. assigned inside a loop/helper)
        const_name = _derive_const_name(var_name, prefix)
        if const_name in used:
            if warnings is not None:
                winner = owner[const_name]
                rank_style = bool(names) and names.get(winner) == names.get(item_id) and winner in names
                if not rank_style:
                    warnings.append(
                        f"header: {prefix}{var_name.upper()} - id {item_id} ({var_name}) lost the short name "
                        f"{const_name} to id {winner} ({var_names.get(winner)}); it is emitted under the "
                        f"unstripped name instead"
                    )
            const_name = f"{prefix}{var_name.upper()}"
        if const_name in used:
            # Belt and suspenders: var_name itself collided too (two different files happened to
            # bind the same Python name to two different ids - unusual, but ids are always unique).
            const_name = f"{const_name}_{item_id}"
        used.add(const_name)
        owner.setdefault(const_name, item_id)
        lines.append(f"    constexpr uint32 {const_name} = {item_id}; // {var_name}")
    return lines


def build_header(class_name: str, dsl_classes: dict, warnings: list[str] | None = None) -> str | None:
    """Returns the header text for one class, or `None` when it has nothing to generate (no
    spells/creatures declared under this class name, and no `const()` calls) - `write_headers`
    then leaves that class with no generated file at all rather than an empty, pointless one."""
    spell_var_names: dict[int, str] = dsl_classes.get("spell_var_names", {})
    creature_var_names: dict[int, str] = dsl_classes.get("creature_var_names", {})

    class_spell_ids = sorted(
        e["id"] for e in dsl_classes.get("spells", []) if e.get("_source_class") == class_name
    )
    class_creature_ids = sorted(
        e["entry"] for e in dsl_classes.get("creature_templates", []) if e.get("_source_class") == class_name
    )
    class_consts = [c for c in dsl_classes.get("consts", []) if c.get("_source_class") == class_name]

    spell_names = {
        e["id"]: e.get("name") for e in dsl_classes.get("spells", []) if e.get("_source_class") == class_name
    }
    spell_lines = _render_id_section(class_spell_ids, spell_var_names, "SPELL_", spell_names, warnings)
    creature_lines = _render_id_section(class_creature_ids, creature_var_names, "NPC_", None, warnings)

    const_lines = []
    for c in sorted(class_consts, key=lambda c: c["name"]):
        literal = _cpp_literal(c["value"], c["cpp_type"])
        doc = f" // {c['doc']}" if c.get("doc") else ""
        const_lines.append(f"    constexpr {c['cpp_type']} {c['name']} = {literal};{doc}")

    if not spell_lines and not creature_lines and not const_lines:
        return None

    namespace = f"{class_name.capitalize()}Data"
    lines = [
        GENERATED_HEADER_MARKER,
        f"// Source: source/classes/{class_name}/ (docs/potency-system.md \"Script numbers\", tier 3; PLAN P2b)",
        "",
        "#pragma once",
        "",
        '#include "Define.h"',
        "",
        f"namespace {namespace}",
        "{",
    ]
    for header, section in (
        ("    // Spell ids", spell_lines),
        ("    // Creature (NPC) ids", creature_lines),
        ("    // const() - hidden script numbers (tier 3)", const_lines),
    ):
        if section:
            lines.append(header)
            lines.extend(section)
            lines.append("")

    while lines[-1] == "":
        lines.pop()
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def write_headers(dsl_classes: dict, out_dir: Path, class_names: tuple[str, ...]) -> list[str]:
    """Writes `<out_dir>/<Class>Data.h` for every name in `class_names` that has something to
    generate. Unlike `lib.potency_sheet`'s `docs/` output, this file is **committed** (the CMake
    build doesn't run Python - PLAN P2b step 2), so `class_names` is an explicit opt-in list
    (`generate.py`'s own `CLASSES_WITH_GENERATED_HEADERS`), not "every class that happens to have
    spells" - adopting the generated header is a deliberate per-class-pass decision (PLAN step 4),
    not a side effect of running `generate.py`."""
    written = []
    for class_name in class_names:
        text = build_header(class_name, dsl_classes)
        if text is None:
            continue
        out_dir.mkdir(parents=True, exist_ok=True)
        path = out_dir / f"{class_name.capitalize()}Data.h"
        path.write_text(text, encoding="utf-8", newline="\n")
        written.append(str(path))
    return written


def check_headers(dsl_classes: dict, out_dir: Path, class_names: tuple[str, ...]) -> list[str]:
    """`generate.py --check` (PLAN P2b step 3): returns one problem line per class whose committed
    header doesn't match what `build_header` would write right now - empty list means every
    generated header is up to date."""
    problems = []
    for class_name in class_names:
        text = build_header(class_name, dsl_classes)
        path = out_dir / f"{class_name.capitalize()}Data.h"
        on_disk = path.read_text(encoding="utf-8") if path.exists() else None
        if text == on_disk:
            continue
        if text is None:
            problems.append(f"{path} exists but source no longer declares anything for it - remove it by hand")
        elif on_disk is None:
            problems.append(f"{path} doesn't exist - run generate.py to create it")
        else:
            problems.append(f"{path} is stale - run generate.py to regenerate it")
    return problems


def collect_warnings(dsl_classes: dict, class_names: tuple[str, ...]) -> list[str]:
    """X2: the `header: ...` short-name-loss warnings for every class in `class_names` that is also in `WARN_CLASSES`, for
    `generate.py` to print as `WARNING: <line>` (both `--check` and the full run). Warnings only -
    never changes what `build_header` writes."""
    warnings: list[str] = []
    for class_name in class_names:
        if class_name in WARN_CLASSES:
            build_header(class_name, dsl_classes, warnings)
    return warnings
