"""
Writes `docs/potency/<class>.md` (docs/potency-system.md's "Potency sheet", PLAN P2 step 6): one
row per potency effect, grouped by the `source/classes/*` file/directory that declared it (tagged
during `lib.dsl.registry.load_classes_dir` as `_source_class` - see that function). Reads the
`_potency` dict `lib.dsl.model.Spell._resolve_potency` already stashed on each potency effect
(a `dataclasses.asdict(ResolvedPotency)` plus `spell_level`/`ticks`) - no math happens here, only
formatting and `lib.potency.simulate_value` calls to show values at a few reference levels.

Like the rest of `docs/`, these sheets are local and not committed - every `generate.py` run
rewrites them from scratch (docs/potency-system.md: "Like the rest of docs/, the sheets are local
and not committed; every generate.py run rewrites them"). Don't add a `.gitignore` exception.
"""

from __future__ import annotations

from pathlib import Path

from . import potency

SHEET_LEVELS = (1, 25, 40, 60, 70, 80)


def _resolved_from_stash(stash: dict) -> potency.ResolvedPotency:
    fields = {f.name for f in potency.ResolvedPotency.__dataclass_fields__.values()}
    return potency.ResolvedPotency(**{k: v for k, v in stash.items() if k in fields})


def _kind_label(stash: dict) -> str:
    if stash["kind"] == "weapon":
        return "weapon"
    return stash["kind"]


def _value_cell(stash: dict, resolved: potency.ResolvedPotency, level: int) -> str:
    spell_level = stash["spell_level"]
    lo = potency.simulate_value(resolved, level, spell_level, roll=1.0)
    if resolved.variance_pct:
        hi = potency.simulate_value(resolved, level, spell_level, roll=1.0 + resolved.variance_pct / 100.0)
        return f"{int(lo)}-{int(hi)}"
    ticks = stash.get("ticks")
    if ticks and ticks > 1:
        return f"{int(lo)} ({int(lo * ticks)} total)"
    return str(int(lo))


def _potency_cell(stash: dict) -> str:
    if stash["kind"] == "weapon":
        return f"{stash['total_potency']:g}% weapon"
    return f"{stash['total_potency']:g}"


def _coefficient_cell(stash: dict) -> str:
    if stash["kind"] == "weapon":
        return "-"
    sp = stash.get("sp_coefficient") or 0.0
    ap = stash.get("ap_coefficient") or 0.0
    if sp and ap:
        return f"sp {sp:.3f} / ap {ap:.3f}"
    if ap:
        return f"ap {ap:.3f}"
    return f"{sp:.3f}"


def build_class_sheet(class_name: str, spell_entries: list[dict]) -> str | None:
    """Returns the Markdown text for one class's sheet, or `None` when the class declared no
    potency effects at all (so `write_sheets` doesn't write an empty file for every class)."""
    rows: list[str] = []
    for entry in sorted(spell_entries, key=lambda e: e["id"]):
        for idx, key in enumerate(("effect1", "effect2", "effect3"), start=1):
            effect = entry.get(key)
            if not effect or "_potency" not in effect:
                continue
            stash = effect["_potency"]
            resolved = _resolved_from_stash(stash)
            t = stash["t_seconds"]
            row = [
                str(entry["id"]),
                entry.get("name", ""),
                str(idx),
                _kind_label(stash),
                _potency_cell(stash),
                f"{t:g}s",
                _coefficient_cell(stash),
            ] + [_value_cell(stash, resolved, level) for level in SHEET_LEVELS]
            rows.append("| " + " | ".join(row) + " |")
    if not rows:
        return None
    header = (
        "| Spell | Name | Effect | Kind | Potency | T | Coefficient | "
        + " | ".join(f"L{lvl}" for lvl in SHEET_LEVELS)
        + " |"
    )
    separator = "|" + "|".join(["---"] * (7 + len(SHEET_LEVELS))) + "|"
    return (
        f"# {class_name.capitalize()} potency\n\n"
        "Generated by `apps/dbc-tools/generate.py` (docs/potency-system.md's \"Potency sheet\") - "
        "not committed, rewritten on every run.\n\n"
        f"{header}\n{separator}\n" + "\n".join(rows) + "\n"
    )


def write_sheets(dsl_classes: dict, out_dir: Path) -> list[str]:
    """Writes one `<out_dir>/<class>.md` per class with at least one potency effect. Returns the
    list of files written, for `generate.py`'s own progress line."""
    by_class: dict[str, list[dict]] = {}
    for entry in dsl_classes.get("spells", []):
        by_class.setdefault(entry.get("_source_class", "unknown"), []).append(entry)

    written = []
    out_dir.mkdir(parents=True, exist_ok=True)
    for class_name, entries in sorted(by_class.items()):
        text = build_class_sheet(class_name, entries)
        if text is None:
            continue
        path = out_dir / f"{class_name}.md"
        path.write_text(text, encoding="utf-8")
        written.append(str(path))
    return written
