"""
Emission of the three plain world-DB spell tables a `source/classes/*` DSL
file can declare alongside a spell - `spell_script_names` (`scripted_by`),
`spell_bonus_data` (`bonus_coefficients`) and `spell_proc` (`procs_on`), all
in `lib/dsl/registry.py`. Before this, every one of them was a separate
hand-written migration next to the C++ it belongs to (see any
`data/sql/updates/db_world/2026_09_*.sql` from the Arcane Mage rework),
which is exactly the "declared in one place, wired in a second, forgot the
second" bug shape the DSL exists to close: a script name with no
`spell_script_names` row never runs and never logs; a custom spell with no
`spell_bonus_data` row silently gets the engine's cast-time-derived
coefficient instead of the one the design doc specifies.

Same mechanics as `trainer_spell`'s path in `generate.py`: each table's
declared rows are diffed against what's already live (a static scan of the
base dump + every migration, via `trainer_state.load_table_rows`) so a
rerun with unchanged source emits nothing, and what does change is rendered
with `sql_out.render_generic_table_block`'s DELETE-then-INSERT on the exact
key tuples. Inherits `load_table_rows`'s "union of INSERTs, no DELETE
replay" limitation - a row deleted by a later migration still reads as
live here, so it can only ever under-emit an unchanged row, never emit a
wrong one.
"""

from __future__ import annotations

from dataclasses import dataclass

from pathlib import Path

from . import sql_dump, sql_out, trainer_state

# Column tuples mirror each table's CREATE TABLE in data/sql/base/db_world/,
# minus the synthetic "id" the registry adds for duplicate-declaration
# bookkeeping (see Registry's docstring).
SPELL_SCRIPT_NAMES_COLUMNS = ("spell_id", "ScriptName")
SPELL_BONUS_DATA_COLUMNS = ("entry", "direct_bonus", "dot_bonus", "ap_bonus", "ap_dot_bonus", "comments")
SPELL_PROC_COLUMNS = (
    "SpellId", "SchoolMask", "SpellFamilyName", "SpellFamilyMask0", "SpellFamilyMask1",
    "SpellFamilyMask2", "ProcFlags", "SpellTypeMask", "SpellPhaseMask", "HitMask",
    "AttributesMask", "DisableEffectsMask", "ProcsPerMinute", "Chance", "Cooldown", "Charges",
)


# First line of every file `generate.py` writes (its `header`). This is the
# prune pass's whole notion of provenance: a row is ours to remove only if a
# past run of this tool emitted it, and marker-bearing files are exactly the
# set of files past runs wrote. Everything else - the base dump, hand-written
# migrations, module SQL - is off limits by construction. Keep in sync with
# `generate.py`'s `header`.
GENERATED_MARKER = "-- Generated by apps/dbc-tools/generate.py"


def _is_generated(path: Path) -> bool:
    """Cheap first-line check; a file that can't be read isn't ours."""
    try:
        with path.open(encoding="utf-8") as fh:
            return fh.readline().startswith(GENERATED_MARKER)
    except OSError:  # pragma: no cover - defensive
        return False


def load_generated_table_rows(table_name: str, key_columns: tuple[str, ...]) -> list[dict]:
    """Rows this tool has emitted and not since removed, replayed in apply
    order across every generated migration still on disk.

    Deliberately *not* `trainer_state.load_table_rows`: that one unions the
    base dump and every migration regardless of author, which is the right
    answer for "what's live" and exactly the wrong one for "what may we
    delete".

    It is also a real **replay** rather than that function's union of
    INSERTs, because the prune pass writes its own DELETEs into these very
    files. Taking the union would re-report every already-pruned row on every
    subsequent run, forever - emitting a redundant DELETE each time and
    writing a migration file even for an otherwise no-op run.

    An unrecognized DELETE shape is treated as "this file may have removed
    anything": the table's emitted set is dropped, which can only make the
    prune *smaller* (nothing gets deleted that shouldn't). Generated files
    only ever contain the shapes `sql_out.py` emits, so this is a guard
    against a future emitter change, not an expected path."""
    fallback_columns: tuple[str, ...] = ()
    base_path = trainer_state.BASE_SQL_DIR / f"{table_name}.sql"
    if base_path.is_file():
        fallback_columns = sql_dump.parse_create_table_columns(base_path, table_name)

    live: dict[tuple, dict] = {}
    for path in trainer_state._migration_files_mentioning(table_name):
        if not _is_generated(path):
            continue
        try:
            for kind, payload in sql_dump.read_table_statements(path, table_name, fallback_columns):
                if kind == "insert":
                    for row in payload:
                        key = _row_key(row, key_columns)
                        if key is not None:
                            live[key] = row
                elif kind == "delete":
                    delete_cols, key_tuples = payload
                    for values in key_tuples:
                        for key in _matching_keys(live, key_columns, delete_cols, values):
                            live.pop(key, None)
                else:  # delete_unparsed
                    print(
                        f"warning: spell_tables.py: {path} has a DELETE on {table_name} in a shape "
                        f"this replay doesn't understand; skipping prune for {table_name}"
                    )
                    return []
        except Exception as exc:  # pragma: no cover - defensive, cf. load_table_rows
            print(f"warning: spell_tables.py: skipping {path} for {table_name}: {exc}")
    return list(live.values())


def _row_key(row: dict, key_columns: tuple[str, ...]) -> tuple | None:
    try:
        return tuple(_normalise(row[c]) for c in key_columns)
    except KeyError:
        return None


def _matching_keys(
    live: dict[tuple, dict], key_columns: tuple[str, ...],
    delete_cols: tuple[str, ...], values: tuple,
) -> list[tuple]:
    """Keys in `live` that a DELETE naming `delete_cols` = `values` removes.

    Usually `delete_cols` is the table's full key and this is a single exact
    hit. It can also be a *prefix* - a single-column `DELETE ... WHERE
    SpellId IN (...)` against a table keyed on more than one column - in
    which case every key sharing those leading values goes."""
    wanted = tuple(_normalise(v) for v in values)
    if delete_cols == key_columns:
        return [wanted] if wanted in live else []
    try:
        idx = [key_columns.index(c) for c in delete_cols]
    except ValueError:
        return []  # a column we don't key on - can't tell what it removes, so remove nothing
    return [k for k in live if tuple(k[i] for i in idx) == wanted]


def load_base_table_rows(table_name: str) -> list[dict]:
    """Stock rows only, straight from the base dump - used to refuse to prune
    a key a past run *overrode* rather than introduced (safety rule 1 of
    `.agents/plans/dbc-tools-prune-pass/dbc-tools-prune-pass.PLAN.md`)."""
    base_path = trainer_state.BASE_SQL_DIR / f"{table_name}.sql"
    if not base_path.is_file():
        return []
    columns = sql_dump.parse_create_table_columns(base_path, table_name)
    return sql_dump.read_table_rows(base_path, table_name, columns)


@dataclass(frozen=True)
class TableSpec:
    name: str
    columns: tuple[str, ...]
    key_columns: tuple[str, ...]
    registry_key: str  # the lib.dsl.registry.Registry attribute holding declared rows


SPELL_TABLES = (
    TableSpec("spell_script_names", SPELL_SCRIPT_NAMES_COLUMNS, ("spell_id", "ScriptName"), "spell_script_names"),
    TableSpec("spell_bonus_data", SPELL_BONUS_DATA_COLUMNS, ("entry",), "spell_bonus_data"),
    TableSpec("spell_proc", SPELL_PROC_COLUMNS, ("SpellId",), "spell_procs"),
)


def _normalise(value):
    """Live rows come back from `sql_dump` with whatever literal shape the
    migration used (`0` vs `0.0`, `NULL` vs `''`); the DSL always produces
    typed Python values. Compare on a common footing so a declaration that
    matches what's live in every way that matters isn't re-emitted over a
    formatting difference."""
    if value is None or value == "":
        return None
    if isinstance(value, (int, float)) and not isinstance(value, bool):
        return float(value)
    return str(value)


def _same_row(existing: dict, declared: dict, columns: tuple[str, ...]) -> bool:
    """A column a hand-written migration left out entirely took the table's
    DEFAULT - `0` for every numeric column in these three tables, `NULL` for
    the one text column (`spell_bonus_data.comments`) - so a missing key on
    the live side compares as that default, not as "unknown"."""
    for c in columns:
        default = 0 if isinstance(declared.get(c), (int, float)) else None
        if _normalise(existing.get(c, default)) != _normalise(declared.get(c)):
            return False
    return True


class SpellTableIndex:
    """Live rows for each of `SPELL_TABLES`, keyed by that table's key
    tuple - built once per `generate.py` run (each table means re-parsing
    every migration that mentions it)."""

    def __init__(
        self,
        existing: dict[str, list[dict]],
        emitted: dict[str, list[dict]] | None = None,
        base: dict[str, list[dict]] | None = None,
    ):
        self._by_key: dict[str, dict[tuple, dict]] = {}
        # Key sets for the prune pass: `_emitted` is what past runs of this
        # tool wrote (the only rows it may remove), `_base` is stock content
        # it must never leave a hole in. Both default empty so an index built
        # the old two-argument way simply has nothing to prune.
        self._emitted: dict[str, set[tuple]] = {}
        self._base: dict[str, set[tuple]] = {}
        for spec in SPELL_TABLES:
            keyed: dict[tuple, dict] = {}
            for row in existing.get(spec.name, []):
                key = self._key(spec, row)
                if key is None:
                    continue  # a migration that inserted a partial column set can't be keyed
                keyed[key] = row  # later migrations win - files are scanned in sorted order
            self._by_key[spec.name] = keyed
            self._emitted[spec.name] = self._key_set(spec, (emitted or {}).get(spec.name, []))
            self._base[spec.name] = self._key_set(spec, (base or {}).get(spec.name, []))

    @staticmethod
    def _key(spec: TableSpec, row: dict) -> tuple | None:
        try:
            return tuple(_normalise(row[c]) for c in spec.key_columns)
        except KeyError:
            return None

    @classmethod
    def _key_set(cls, spec: TableSpec, rows: list[dict]) -> set[tuple]:
        return {k for k in (cls._key(spec, r) for r in rows) if k is not None}

    def rows_to_emit(self, spec: TableSpec, declared: list[dict]) -> list[dict]:
        """`declared` minus anything already live with identical values."""
        keyed = self._by_key.get(spec.name, {})
        out = []
        for row in declared:
            key = tuple(_normalise(row[c]) for c in spec.key_columns)
            existing = keyed.get(key)
            if existing is not None and _same_row(existing, row, spec.columns):
                continue
            out.append(row)
        return out


    def rows_to_prune(self, spec: TableSpec, declared: list[dict]) -> PruneResult:
        """Keys a past run emitted that `declared` no longer claims.

        Two refusals, both from the PLAN's safety rules:

        * **Circuit breaker** - a table with an emitted history but *zero*
          declarations this run almost certainly means the source failed to
          load, not that every row was deliberately retired. Pruning then
          would wipe the table's whole managed surface, so refuse the table
          outright.
        * **Base overlap** - the key also exists in the stock dump, so a past
          run overrode a stock row instead of adding a new one. A DELETE would
          leave nothing where stock had something (only reachable for the
          single-key tables; `spell_script_names` is keyed on the
          spell/name pair, so a differently named stock script is a different
          key). Report it for a human instead of guessing."""
        emitted = self._emitted.get(spec.name, set())
        if not emitted:
            return PruneResult(spec, [], [], False)
        declared_keys = self._key_set(spec, declared)
        if not declared_keys:
            return PruneResult(spec, [], [], True)
        orphans = emitted - declared_keys
        base = self._base.get(spec.name, set())
        prunable = sql_out.stable_key_sort(k for k in orphans if k not in base)
        blocked = sql_out.stable_key_sort(k for k in orphans if k in base)
        return PruneResult(spec, prunable, blocked, False)


@dataclass(frozen=True)
class PruneResult:
    spec: TableSpec
    keys: list[tuple]           # safe to DELETE
    base_blocked: list[tuple]   # orphaned, but stock also owns the key - needs a human
    breaker_tripped: bool       # zero declarations for a table with history - refused


# Why an orphan in each table is not merely untidy - quoted into the emitted
# migration so the DELETE explains itself to whoever reads it later.
_PRUNE_WHY = {
    "spell_script_names": 'Left in place, a row naming a ScriptName that no\n'
                          '-- longer exists in C++ logs "Scriptname ... not found" at every boot.',
    "spell_proc": "Left in place, a stale row keeps a proc chance\n"
                  "-- alive that no declared script handles.",
    "spell_bonus_data": "Left in place, a stale row keeps overriding the\n"
                        "-- engine's own spell coefficient.",
}
_PRUNE_WHY_DEFAULT = "Left in place it keeps applying."


def render_prune_blocks(
    index: SpellTableIndex, dsl_classes: dict[str, list[dict]]
) -> tuple[list[str], list[str]]:
    """`(sql_blocks, report_lines)`. A prune is never silent: every removed
    row, every base-blocked orphan and every tripped breaker gets a line, and
    `generate.py` prints them all."""
    blocks: list[str] = []
    report: list[str] = []
    for spec in SPELL_TABLES:
        result = index.rows_to_prune(spec, dsl_classes.get(spec.registry_key, []))
        if result.breaker_tripped:
            report.append(
                f"prune: SKIPPED {spec.name} - it has rows from previous runs but this run "
                f"declared none. Refusing to delete the lot; check source/classes/* loaded."
            )
            continue
        for key in result.base_blocked:
            report.append(
                f"prune: NOT removing {spec.name} {_key_text(spec, key)} - no longer declared, "
                f"but the stock dump owns this key too, so deleting it would leave a hole where "
                f"AzerothCore has a row. Resolve by hand."
            )
        if not result.keys:
            continue
        for key in result.keys:
            report.append(f"prune: removing {spec.name} {_key_text(spec, key)} - no longer declared")
        comment = (
            f"-- Prune: {len(result.keys)} {spec.name} row(s) emitted by an earlier "
            f"generate.py run that source/classes/*\n"
            f"-- no longer declares. {_PRUNE_WHY.get(spec.name, _PRUNE_WHY_DEFAULT)}"
        )
        blocks.append(
            sql_out.render_delete_only_block(spec.name, spec.key_columns, result.keys, comment)
        )
    return blocks, report


def _key_text(spec: TableSpec, key: tuple) -> str:
    """`(spell_id=17322, ScriptName='spell_pri_shadow_reach')` - for humans.
    Key parts arrive `_normalise`d, so ints are floats by the time we see
    them; render whole numbers without the `.0`."""
    parts = []
    for column, value in zip(spec.key_columns, key):
        if isinstance(value, float) and value.is_integer():
            value = int(value)
        parts.append(f"{column}={value!r}" if isinstance(value, str) else f"{column}={value}")
    return "(" + ", ".join(parts) + ")"


def load_spell_table_index() -> SpellTableIndex:
    return SpellTableIndex(
        {spec.name: trainer_state.load_table_rows(spec.name) for spec in SPELL_TABLES},
        emitted={spec.name: load_generated_table_rows(spec.name, spec.key_columns) for spec in SPELL_TABLES},
        base={spec.name: load_base_table_rows(spec.name) for spec in SPELL_TABLES},
    )


def render_blocks(index: SpellTableIndex, dsl_classes: dict[str, list[dict]]) -> list[str]:
    """One pre-rendered SQL block per table that has something new/changed
    to say, in `SPELL_TABLES` order, ready for `sql_out.emit_pending_sql`'s
    `extra_blocks`. Empty strings (nothing to emit) are dropped."""
    blocks = []
    for spec in SPELL_TABLES:
        rows = index.rows_to_emit(spec, dsl_classes.get(spec.registry_key, []))
        block = sql_out.render_generic_table_block(spec.name, spec.columns, spec.key_columns, rows)
        if block:
            blocks.append(block)
    return blocks


def count_declared(dsl_classes: dict[str, list[dict]]) -> dict[str, int]:
    return {spec.name: len(dsl_classes.get(spec.registry_key, [])) for spec in SPELL_TABLES}
