-- Phase 3: prices the 4 custom secondary stats (Mastery/Versatility/Cooldown
-- Haste/Proc Chance -- ITEM_MOD ids 22/23/24/33, repurposed from dead
-- "Hit Taken *" rating slots, see ItemTemplate.h) into item_stat_cost for the
-- first time. Weighted equal to Crit (stat_type 32: cost 1, is_primary 0) per
-- direct instruction -- all four custom stats carry the same weight as Crit at
-- the end of the day. Without this, no item_budget_template can allocate to
-- them (ItemBudget.cpp's own validation flags any that try), and -- confirmed
-- live -- any item hand-authored with one of these stats gets it silently
-- stripped the moment it's regenerated by this system, since the conversion
-- classifier only keeps stat types item_stat_cost knows how to price.

DELETE FROM `item_stat_cost` WHERE `stat_type` IN (22, 23, 24, 33);
INSERT INTO `item_stat_cost` (`stat_type`, `cost`, `is_primary`) VALUES
(22, 1, 0), -- Mastery
(23, 1, 0), -- Versatility
(24, 1, 0), -- Cooldown Haste
(33, 1, 0); -- Proc Chance
