-- DB update 2026_09_23_02 -> 2026_09_23_03
-- Priest Phase 1 model/animation VFX for Angelic Feather, Divine Star, Halo, Void Eruption, and
-- Leap of Faith - mined from the Ascension client backup, same source already used for these
-- spells' tooltip icons (build_patch_i.py). Generated by apps/dbc-tools/patch_priest_vfx_models.py
-- (run it, don't hand-edit this file - see that script's own docstring for full sourcing/
-- attribution notes, including why Power Word: Barrier needed no new row at all: its visual chain
-- turned out to already be genuine, unused stock 3.3.5a client data, wired directly via
-- priest_spells.py's SpellVisualID_1=13210).
--
-- Squash cleanup (2026-09-20): this file now also carries what was originally a separate
-- live-playtest-fix migration (rev_1789887523716570045.sql, deleted as part of this squash - see
-- git history if needed), folded in because both touched overlapping ID ranges in the same table
-- (spellvisual_dbc 90011-90016 vs this file's superset 90011-90017) - keeping them split only
-- preserved churn, not information. The spellvisual_dbc block below is the final, complete state
-- (includes SV_POWER_WORD_BARRIER/90017, wiring the real untouched stock dome kit 12286 via
-- PersistentAreaKit instead of ChannelKit - the field real ground-zone spells like Death and Decay
-- actually use - and SV_VOID_ERUPTION/90015's CastKit pointing at stock "Shadow Nova"
-- (SpellVisualEffectName 3112) instead of the original custom-mined cast model, per the user's own
-- request). These 4 tables (spellvisual_dbc/creaturemodeldata_dbc/creaturedisplayinfo_dbc/
-- gameobjectdisplayinfo_dbc) are the SQL overlay AzerothCore actually loads server-side
-- (DBCStores.cpp's LOAD_DBC calls) - SpellVisualKit.dbc/SpellVisualEffectName.dbc are client-only,
-- no SQL counterpart, shipped purely through the matching patch-M.mpq client patch.
DELETE FROM `spellvisual_dbc` WHERE `ID` BETWEEN 90011 AND 90017;
INSERT INTO `spellvisual_dbc` (`ID`, `PrecastKit`, `CastKit`, `ImpactKit`, `StateKit`, `StateDoneKit`, `ChannelKit`, `HasMissile`, `MissileModel`, `MissilePathType`, `MissileDestinationAttachment`, `MissileSound`, `AnimEventSoundID`, `Flags`, `CasterImpactKit`, `TargetImpactKit`, `MissileAttachment`, `MissileFollowGroundHeight`, `MissileFollowGroundDropSpeed`, `MissileFollowGroundApproach`, `MissileFollowGroundFlags`, `MissileMotion`, `MissileTargetingKit`, `InstantAreaKit`, `ImpactAreaKit`, `PersistentAreaKit`, `MissileCastOffsetX`, `MissileCastOffsetY`, `MissileCastOffsetZ`, `MissileImpactOffsetX`, `MissileImpactOffsetY`, `MissileImpactOffsetZ`) VALUES
(90011, 99, 90008, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(90012, 90009, 90010, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(90013, 0, 0, 90011, 0, 0, 0, 0, 0, 0, 34, 0, 0, 576, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(90014, 193, 90012, 0, 3153, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(90015, 90013, 90014, 2350, 0, 0, 0, 1, 90016, 0, 1, 3015, 0, 1, 0, 0, 0, 0, 0, 0, 0, 13376, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(90016, 0, 90015, 90016, 90017, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(90017, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12286, 0, 0, 0, 0, 0, 0);

DELETE FROM `creaturemodeldata_dbc` WHERE `ID` BETWEEN 90004 AND 90004;
INSERT INTO `creaturemodeldata_dbc` (`ID`, `Flags`, `ModelName`, `SizeClass`, `ModelScale`, `BloodID`, `FootprintTextureID`, `FootprintTextureLength`, `FootprintTextureWidth`, `FootprintParticleScale`, `FoleyMaterialID`, `FootstepShakeSize`, `DeathThudShakeSize`, `SoundID`, `CollisionWidth`, `CollisionHeight`, `MountHeight`, `GeoBoxMinX`, `GeoBoxMinY`, `GeoBoxMinZ`, `GeoBoxMaxX`, `GeoBoxMaxY`, `GeoBoxMaxZ`, `WorldEffectScale`, `AttachedEffectScale`, `MissileCollisionRadius`, `MissileCollisionPush`, `MissileCollisionRaise`) VALUES
(90004, 2, 'SPELLS\\Priest_DivineStar_Missile_Yellow.mdx', 1, 1.0, 1, 0, 0, 0, 1.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1.0, 1.0, 0, 0, 0);

DELETE FROM `creaturedisplayinfo_dbc` WHERE `ID` BETWEEN 90004 AND 90004;
INSERT INTO `creaturedisplayinfo_dbc` (`ID`, `ModelID`, `SoundID`, `ExtendedDisplayInfoID`, `CreatureModelScale`, `CreatureModelAlpha`, `TextureVariation_1`, `TextureVariation_2`, `TextureVariation_3`, `PortraitTextureName`, `BloodLevel`, `BloodID`, `NPCSoundID`, `ParticleColorID`, `CreatureGeosetData`, `ObjectEffectPackageID`) VALUES
(90004, 90004, 0, 0, 1.0, 255, NULL, NULL, NULL, NULL, 1, 0, 0, 0, 0, 0);

DELETE FROM `gameobjectdisplayinfo_dbc` WHERE `ID` BETWEEN 90001 AND 90001;
INSERT INTO `gameobjectdisplayinfo_dbc` (`ID`, `ModelName`, `Sound_1`, `Sound_2`, `Sound_3`, `Sound_4`, `Sound_5`, `Sound_6`, `Sound_7`, `Sound_8`, `Sound_9`, `Sound_10`, `GeoBoxMinX`, `GeoBoxMinY`, `GeoBoxMinZ`, `GeoBoxMaxX`, `GeoBoxMaxY`, `GeoBoxMaxZ`, `ObjectEffectPackageID`) VALUES
(90001, 'SPELLS\\Priest_AngelicFeather_State.M2', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -2.257110118865967, -2.38496994972229, -0.10669799894094467, 2.4491798877716064, 2.3395800590515137, 3.930310010910034, 0);
