-- Generated by apps/dbc-tools/generate.py — DO NOT hand-edit.
-- Source of truth: apps/dbc-tools/source/items.csv.
-- Regenerate with: python3 apps/dbc-tools/generate.py
--
-- Hand-extracted from generate.py's full output this run (which also swept up 376
-- unrelated, still-in-progress spell edits from source/spells/*.csv - not this
-- change's to ship). This is the `item_dbc` block only; content is identical to
-- (and already fully covered by, so a no-op replay) rev_1788562122430972052.sql's
-- hand-written item_dbc rows, now also folded into the generator's own reserved
-- `item` ID block (source/ids.yaml, 70000-79999) plus row 70001 (Mythic Plus
-- Keystone), which predates this pipeline touching Item.dbc at all.

DELETE FROM `item_dbc` WHERE `ID` BETWEEN 70000 AND 79999;
INSERT INTO `item_dbc` (`ID`, `ClassID`, `SubclassID`, `Sound_Override_Subclassid`, `Material`, `DisplayInfoID`, `InventoryType`, `SheatheType`) VALUES
(70001, 15, 0, -1, -1, 58859, 0, 0),
(70100, 4, 0, -1, 3, 31664, 11, 0),
(70101, 4, 0, -1, 3, 31664, 11, 0),
(70102, 4, 0, -1, 3, 31664, 11, 0),
(70103, 4, 0, -1, 3, 31664, 11, 0);
