"""
Unit tests for `codestyle-sql.py`'s `insert_delete_safety_check`, specifically the T1
(.agents/plans/warlock-rework/warlock-rework.T1-HANDOFF.md) exception for an upsert
(`INSERT ... ON DUPLICATE KEY UPDATE ...`) into a `not_delete` table (creature_template
especially) - apps/dbc-tools' generate.py now emits exactly this shape for creature_template
(lib/dsl/registry.py's creature_template(), lib/sql_out.py's render_upsert_block).

`codestyle-sql.py` isn't a normal importable module - its top level does real directory
globbing and, at the very end, calls `parsing_file(all_files)` (which does a real `git fetch`).
This loads everything *above* that final call by source, via `exec`, into an isolated namespace -
the same trick `apps/dbc-tools`' own generate.py-adjacent tests use for un-importable scripts -
so `insert_delete_safety_check` can be exercised directly against a scratch file, never against
`data/sql/updates/pending_db_*`.

Run directly:

    python3 apps/codestyle/test_codestyle_sql.py
"""

from __future__ import annotations

import io
import tempfile
import unittest
from pathlib import Path

SCRIPT_PATH = Path(__file__).resolve().parent / "codestyle-sql.py"
_STOP_MARKER = "# Collect all files from matching directories"


def _load_checks() -> dict:
    source = SCRIPT_PATH.read_text(encoding="utf-8").split(_STOP_MARKER)[0]
    ns: dict = {"__name__": "codestyle_sql_under_test"}
    exec(compile(source, str(SCRIPT_PATH), "exec"), ns)
    return ns


def _check(sql_text: str) -> tuple[bool, str]:
    """Runs `insert_delete_safety_check` against `sql_text` in a fresh scratch file (never
    `pending_db_*`) and returns `(passed, captured_stdout)`."""
    ns = _load_checks()
    with tempfile.NamedTemporaryFile("w", suffix=".sql", delete=False) as f:
        f.write(sql_text)
        path = Path(f.name)
    try:
        buf = io.StringIO()
        import contextlib
        with contextlib.redirect_stdout(buf):
            with path.open(encoding="utf-8") as fh:
                ns["insert_delete_safety_check"](fh, str(path))
        passed = ns["results"]["INSERT, UPDATE & DELETE safety usage check"] == "Passed"
        return passed, buf.getvalue()
    finally:
        path.unlink()


GENERATED_HEADER = "-- Generated by apps/dbc-tools/generate.py — DO NOT hand-edit.\n\n"


class UpsertIntoNotDeleteTableTest(unittest.TestCase):
    def test_creature_template_upsert_passes_with_no_preceding_delete(self):
        passed, output = _check(
            GENERATED_HEADER
            + "INSERT INTO `creature_template` (`entry`, `name`) VALUES\n"
            "(300170, 'Chaos Rift') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`);\n"
        )
        self.assertTrue(passed, output)

    def test_multi_row_upsert_with_on_duplicate_on_the_final_line_passes(self):
        passed, output = _check(
            GENERATED_HEADER
            + "INSERT INTO `creature_template` (`entry`, `name`) VALUES\n"
            "(300170, 'Chaos Rift'),\n"
            "(300171, 'Chaos Rift 2') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`);\n"
        )
        self.assertTrue(passed, output)

    def test_real_tentacle_migration_file_passes(self):
        tentacle = (
            Path(__file__).resolve().parents[2]
            / "data" / "sql" / "updates" / "db_world" / "2026_09_23_12.sql"
        )
        passed, output = _check(tentacle.read_text(encoding="utf-8"))
        self.assertTrue(passed, output)

    def test_plain_insert_into_not_delete_table_without_upsert_still_fails(self):
        passed, output = _check(
            GENERATED_HEADER
            + "INSERT INTO `creature_template` (`entry`, `name`) VALUES\n(300170, 'Chaos Rift');\n"
        )
        self.assertFalse(passed)
        self.assertIn("No DELETE keyword found before the INSERT", output)

    def test_plain_insert_into_an_ordinary_table_still_fails(self):
        passed, output = _check(
            GENERATED_HEADER
            + "INSERT INTO `trainer_spell` (`TrainerId`, `SpellId`) VALUES\n(212, 300170);\n"
        )
        self.assertFalse(passed)
        self.assertIn("No DELETE keyword found before the INSERT", output)

    def test_delete_from_creature_template_is_still_forbidden_even_with_on_duplicate_elsewhere(self):
        # The upsert exception only ever waives the missing-DELETE rule - it must never waive the
        # separate, unconditional "don't DELETE a not_delete table" rule.
        passed, output = _check(
            GENERATED_HEADER
            + "DELETE FROM `creature_template` WHERE `entry` = 300170;\n"
            "INSERT INTO `creature_template` (`entry`, `name`) VALUES\n"
            "(300170, 'Chaos Rift') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`);\n"
        )
        self.assertFalse(passed)
        self.assertIn("should not be deleted", output)

    def test_upsert_into_an_ordinary_table_is_not_exempted(self):
        # The exception is narrow: it only applies to a `not_delete` table. An upsert-shaped INSERT
        # into a normal table still needs its DELETE, same as any other INSERT.
        passed, output = _check(
            GENERATED_HEADER
            + "INSERT INTO `trainer_spell` (`TrainerId`, `SpellId`) VALUES\n"
            "(212, 300170) ON DUPLICATE KEY UPDATE `SpellId` = VALUES(`SpellId`);\n"
        )
        self.assertFalse(passed)
        self.assertIn("No DELETE keyword found before the INSERT", output)


if __name__ == "__main__":
    unittest.main()
